# -*- coding: utf-8 -*-
"""Assignment1-Week4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mrx0-CTXQzg6LOrRAPnn20mYP6NHk3VN
"""

# Commented out IPython magic to ensure Python compatibility.
#Question 1. Load the Loan Prediction dataset and perform an initial analysis.
import pandas as pd
df=pd.read_csv("data6.csv")
#1. Display the first 10 records.
df.head(10)
#2. Identify all features and the target variable.
print(df.columns)
#3. Determine the number of records and attributes.
print(df.shape)
#4. Check for missing values.
print(df.isnull().sum())
#5. Describe the statistical properties of numerical features.
df.describe()

#Question 2. Perform data preprocessing.
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
#1. Handle missing values using appropriate techniques.
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])
df['Married'] = df['Married'].fillna(df['Married'].mode()[0])
df['Dependents'] = df['Dependents'].fillna(df['Dependents'].mode()[0])
df['Self_Employed'] = df['Self_Employed'].fillna(df['Self_Employed'].mode()[0])
df['LoanAmount'] = df['LoanAmount'].fillna(df['LoanAmount'].mean())
df['Loan_Amount_Term'] = df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].mean())
df['Credit_History'] = df['Credit_History'].fillna(df['Credit_History'].mean())
print(df.isnull().sum())
#2. Convert categorical variables into numerical format.
df['Gender']=le.fit_transform(df['Gender'])
df['Married']=le.fit_transform(df['Married'])
df['Education']=le.fit_transform(df['Education'])
df['Self_Employed']=le.fit_transform(df['Self_Employed'])
df['Property_Area']=le.fit_transform(df['Property_Area'])
df['Loan_Status']=le.fit_transform(df['Loan_Status'])
df.head(10)
#3. Normalize or standardize numerical features (if required).
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
df['Dependents'] = df['Dependents'].replace('3+', 3)
df['Dependents'] = df['Dependents'].astype(int)
df['ApplicantIncome']=sc.fit_transform(df[['ApplicantIncome']])
df['CoapplicantIncome']=sc.fit_transform(df[['CoapplicantIncome']])
df.head()
#4. Create the final feature matrix and target variable.
x=df.drop(['Loan_Status','Loan_ID'],axis=1)
y=df['Loan_Status']
print(x)
print(y)

#Question 3. Perform exploratory data analysis to understand factors affecting loan approval.
#Create at least five visualizations, such as:
import matplotlib.pyplot as plt
import matplotlib
import seaborn as sns
import plotly.express as px
# %matplotlib inline
sns.set_style('darkgrid')
matplotlib.rcParams ['font.size' ] = 14
matplotlib.rcParams['figure.figsize'] = (10, 6)
matplotlib.rcParams['figure.facecolor' ] = '#00000000'
#1. Loan approval distribution.
fig =px.histogram(df,
    x="Loan_Status",
    color="Loan_Status",
    title="Loan Approval Distribution")
fig.update_layout(bargap=0.1)
fig.show()
#2. Applicant income vs loan approval.
fig = px.histogram(df,
    x="ApplicantIncome",
    marginal='box',
    color="Loan_Status",
    barmode="group",
    color_discrete_sequence=['green', 'grey'],
    title="Applicant Income vs Loan Approval")
fig.update_layout(bargap=0.1)
fig.show()
#3. Credit history vs loan approval.
fig = px.histogram(df,
    x="Credit_History",
    marginal='box',
    color="Loan_Status",
    barmode="group",
    color_discrete_sequence=['green', 'grey'],
    title="Credit History vs Loan Approval")
fig.update_layout(bargap=0.1)
fig.show()
#4. Education level vs loan approval.
fig = px.histogram(df,
    x="Education",
    marginal='box',
    color="Loan_Status",
    barmode="group",
    color_discrete_sequence=['blue', 'grey'],
    title="Education vs Loan Approval")
fig.update_layout(bargap=0.1)
fig.show()
#5. Property area vs loan approval.
fig = px.histogram(df,
    x="Property_Area",
    marginal='box',
    color="Loan_Status",
    barmode="group",
    color_discrete_sequence=['red', 'grey'],
    title="Property Area vs Loan Approval")
fig.update_layout(bargap=0.1)
fig.show()
'''1. Which feature appears most influential in loan approval?
Credit History And Applicant Income, because applicants with a good credit history and Income are approved much more frequently.

2. What patterns can be observed from the visualizations?
The visualizations show that applicants with higher incomes generally have better approval chances.
Graduates and applicants from Semiurban areas show slightly higher approval rates.
However, Credit History has the strongest impact on loan approval compared to the other features.'''

#Question 4. Split the dataset into training and testing sets (80:20).
import numpy as np
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
#Train the following models:
#1. Logistic Regression
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
pred=lr.predict(x_test)
print(accuracy_score(y_test,pred))
print(confusion_matrix(y_test,pred))
print(precision_score(y_test,pred))
print(recall_score(y_test,pred))
print(f1_score(y_test,pred))
#2. Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
pred1=dt.predict(x_test)
print(accuracy_score(y_test,pred1))
print(confusion_matrix(y_test,pred1))
print(precision_score(y_test,pred1))
print(recall_score(y_test,pred1))
print(f1_score(y_test,pred1))
#3. Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
pred2=rf.predict(x_test)
print(accuracy_score(y_test,pred2))
print(confusion_matrix(y_test,pred2))
print(precision_score(y_test,pred2))
print(recall_score(y_test,pred2))
print(f1_score(y_test,pred2))
'''Question 5. Based on the performance metrics:
1. Identify the best-performing model.
The Logistic Regression model performed the best, achieving the highest accuracy (85.37%) and F1-score (0.91).

2. Justify your choice using evaluation metrics.
Logistic Regression was selected because it achieved the highest accuracy (85.37%), recall (97.85%), and F1-score (0.91),
indicating the best overall prediction performance.

3. Discuss the strengths and limitations of each model.
Logistic Regression is simple, fast, and accurate but may not capture complex patterns.
Decision Tree is easy to interpret but may overfit and showed the lowest accuracy
.Random Forest reduces overfitting and performed better than the Decision Tree but was slightly less accurate than Logistic Regression.
'''
#Question 6. Apply Stratified 5-Fold Cross Validation to all three models.
from sklearn.model_selection import cross_val_score
#1. Compute accuracy for each fold.
lr_scores = cross_val_score(lr, x, y, cv=5)
dt_scores = cross_val_score(dt, x, y, cv=5)
rf_scores = cross_val_score(rf, x, y, cv=5)
print("Logistic Regression Scores:", lr_scores)
print("Decision Tree Scores:", dt_scores)
print("Random Forest Scores:", rf_scores)
#2. Calculate mean accuracy and standard deviation.
lr_mean = np.mean(lr_scores)
lr_std = np.std(lr_scores)
dt_mean = np.mean(dt_scores)
dt_std = np.std(dt_scores)
rf_mean = np.mean(rf_scores)
rf_std = np.std(rf_scores)
#3. Compare cross-validation results with the train-test split results.
print("Logistic Regression:")
print("Mean Accuracy:", lr_mean)
print("Standard Deviation:", lr_std)
print("Decision Tree:")
print("Mean Accuracy:", dt_mean)
print("Standard Deviation:", dt_std)
print("Random Forest:")
print("Mean Accuracy:", rf_mean)
print("Standard Deviation:", rf_std)

'''1. Why is Stratified K-Fold preferred for this dataset?
Stratified K-Fold maintains the same class distribution in each fold, providing a fair and reliable evaluation of the model.

2. Which model shows the most consistent performance?
Logistic Regression shows the most consistent performance because it has the highest mean accuracy
and the lowest variation across the folds (based on your cross-validation results).'''

#Question 7. Perform hyperparameter tuning on the Random Forest Classifier using GridSearchCV. Tune the following parameters:
#n_estimators = [50, 100, 200]
#max_depth = [3, 5, 10]
#min_samples_split = [2, 5, 10]
from sklearn.model_selection import GridSearchCV
# Define the parameter grid
#Tasks:
#1. Identify the best parameter combination.
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [3, 5, 10],
    'min_samples_split': [2, 5, 10]}
# Create a Random Forest Classifier
rf = RandomForestClassifier()
# Create a GridSearchCV object
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=5)
# Fit the GridSearchCV object to the data
grid_search.fit(x_train, y_train)
#2. Report the best cross-validation score.
print("Best Cross-Validation Score:", grid_search.best_score_)
#3. Report the best parameters.
print("Best Parameters:", grid_search.best_params_)
#3. Evaluate the tuned model on the test set.
# Best Random Forest model
best_rf = grid_search.best_estimator_
# Predict on test set
y_pred = best_rf.predict(x_test)
# Evaluate the tuned model
print("Test Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))
'''Compare:
Model performance before tuning
Before Tuning:
The Random Forest model used default parameters and achieved good performance, but it was not optimized.

Model performance after tuning
After Tuning:
After applying GridSearchCV, the model used the best hyperparameters and achieved improved or more optimized performance, making it more reliable for prediction'''

#Question 8. Train three Decision Tree models using:
#max_depth = 2
#max_depth = 5
#max_depth = 15
#For each model:
#1. Compute training accuracy.
#2. Compute testing accuracy.
#3. Compare the results.
# max_depth = 2
dt2 = DecisionTreeClassifier(max_depth=2)
dt2.fit(x_train, y_train)
train_pred2 = dt2.predict(x_train)
test_pred2 = dt2.predict(x_test)
print("Max Depth = 2")
print("Training Accuracy:", accuracy_score(y_train, train_pred2))
print("Testing Accuracy:", accuracy_score(y_test, test_pred2))

# max_depth = 5
dt5 = DecisionTreeClassifier(max_depth=5)
dt5.fit(x_train, y_train)
train_pred5 = dt5.predict(x_train)
test_pred5 = dt5.predict(x_test)
print("\nMax Depth = 5")
print("Training Accuracy:", accuracy_score(y_train, train_pred5))
print("Testing Accuracy:", accuracy_score(y_test, test_pred5))

# max_depth = 15
dt15 = DecisionTreeClassifier(max_depth=15)
dt15.fit(x_train, y_train)
train_pred15 = dt15.predict(x_train)
test_pred15 = dt15.predict(x_test)
print("\nMax Depth = 15")
print("Training Accuracy:", accuracy_score(y_train, train_pred15))
print("Testing Accuracy:", accuracy_score(y_test, test_pred15))

'''1. Which model exhibits underfitting?
The Decision Tree with max_depth = 2 exhibits underfitting because it is too simple to capture the patterns in the data,
resulting in lower training and testing accuracy.

2. Which model exhibits overfitting?
The Decision Tree with max_depth = 15 exhibits overfitting because it learns the training data too closely,
leading to very high training accuracy but poorer performance on the test data.

3. Which model provides the best balance between bias and variance?
The Decision Tree with max_depth = 5 provides the best balance between bias and variance,
as it generalizes well and achieves a good balance between training and testing accuracy.'''

